### ISSUE TITLE
Update to latest OpenCV Version, etc.

### ISSUE THREAD

**Issue by avipars** [Ibujah/androidcv_test#1]
I got your demo to work, and updated to the latest OpenCV version.  I want to make a pull request and provide the newest API calls, etc... 

It's standard practice to open an issue before, so i figured  I'll do the same.

**Comment by avipars** [comment]
I put it here since I couldn't make a pull request from Android Studio: https://github.com/avipars/androidcv_test_avi/ I can transfer the ownership to you, or if you can help me merge it with your branch, I can certainly do that.

**Comment by Ibujah** [comment]
If you want to do a pull request, no problem !
How did you find my repo ?

**Comment by avipars** [comment]
I needed a grabcut algorithm to remove backgrounds of images for an internship I'm doing. Android specifically. I could only find one or two and this was the better one. Android Studio was giving me some errors when submitting a pull request, so I had to create a new repo. I can transfer the ownership, or if you help me, we can merge the changes. Or just make a new branch...

**Comment by Ibujah** [comment]
Well I think it would be overcomplicated to to this like that ^^'. And maybe it would not be so useful, as for me it is just a test repository. So you can use it as a basis for you work, but I'll let it like this :)

**Comment by avipars** [comment]
That's not a problem. I'm wondering if you know from your repo, if I can
crop/export an image based on what is seen in your app? So only the
foreground object will be shown for example?

**Comment by Ibujah** [comment]
For this I think that it's possible with OpenCV functions. Well I'll close the issue, as there is nothing more to discuss about a merge :)
